
apiVersion: v1
data:
  local--kafka: eyJrYWZrYV9hZG1pbiI6ImFkbWluOmFkbWluLXNlY3JldCIsImthZmthX3VzZXJfMSI6InVzZXJfMTp1c2VyMXBhc3MiLCJrYWZrYV91c2VyXzIiOiJ1c2VyXzI6dXNlcjJwYXNzIiwia2Fma2FfdXNlcl8zIjoibXktdXNlcjpteXVzZXJwYXNzIn0=
kind: Secret
metadata:
  labels:
    fwss.freshworks.com/secrets-managed: "true"
  name: local--kafka
type: Opaque